---
- name: Set up development environment for students
  hosts: all
  become: yes
  roles:
    - role: student
    - role: common_soft
    - role: kumir
    - role: database
    # - role: reboot
    # - role: spyder