---
- name: Установка QT
  apt:
    name:
      - build-essential
      - qtcreator
      - mesa-common-dev
      - qt5-qmake
      - cmake
      - qt5-doc
      - qt5-doc-html
      - qtbase5-dev
      - qtbase5-dev-tools
      - qtbase5-doc
      - qtbase5-doc-html
      - qtbase5-examples
      - libqt5charts5-dev
      - qtcharts5-doc
      - qtcharts5-doc-html
      - qtcharts5-examples
      - libqt5svg5-dev
      - libqt5x11extras5-dev
      - qtscript5-dev
      # - libssl-dev
      # - qttools5-dev 
      # - qttools5-dev-tools 
      # - qtmultimedia5-dev 
      # - libqt5webkit5-dev 
      # - libsdl2-dev 
      # - libasound2 
      # - libxmu-dev 
      # - libxi-dev 
      # - freeglut3-dev 
      # - libasound2-dev 
      # - libjack-jackd2-dev 
      # - libxrandr-dev 
      # - libqt5xmlpatterns5-dev 
    state: present
    update_cache: yes

- name: Установка Snap
  apt:
    name: snapd
    state: present
    update_cache: yes

- name: Установка Libre Office + Libre Base
  apt:
    name:
      - libreoffice
      - libreoffice-base
    state: present
    update_cache: yes

- name: Установка VSCode
  snap:
    name: code
    state: present
    classic: yes
- name: Установка GIMP
  apt:
    name:
      - gimp
      - gimp-plugin-registry
    state: present
    update_cache: yes

- name: Установка Git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Установка Htop
  apt:
    name: htop
    state: present
    update_cache: yes

- name: Установка Traceroute
  apt:
    name: traceroute
    state: present
    update_cache: yes

- name: Установка Python3
  apt:
    name:
      - python3-pip
    state: present
    update_cache: yes

- name: Установка Octave
  apt:
    name: octave
    state: present
    update_cache: yes

- name: Установка GNU Radio
  apt:
    name: gnuradio
    state: present
    update_cache: yes

- name: Установка русской раскладки
  apt:
    name: 
    - language-pack-ru
    - language-pack-gnome-ru
    - language-pack-kde-ru
    - firefox-locale-ru
    - libreoffice-l10n-ru 
    - libreoffice-help-ru
    - gimp-help-ru
    - hunspell-ru
    - mythes-ru
    state: present
    update_cache: yes

- name: Обновление языка
  shell: |
    sudo update-locale LANG=ru_RU.UTF-8



# TODO: нужно доделать
# - name: Настройка русской раскладки через gsettings
#   shell: |
#     gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('xkb', 'ru')]"

# - name: restart pulse audio
#   shell: |
#     gsettings set org.gnome.desktop.input-sources sources "[('xkb', 'us'), ('xkb', 'ru')]"
#   args:
#     executable: /bin/bash
#   become: true
#   become_method: sudo
#   become_user: student