---
- name: Configure Spyder for inline plotting
  hosts: all
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - spyder
          - python3-matplotlib
          - python3-ipython
        state: present
        update_cache: yes

    - name: Create Spyder config directory
      file:
        path: ~/.config/spyder-py3
        state: directory
        mode: '0755'

    - name: Configure Spyder for inline plots
      ini_file:
        path: ~/.config/spyder-py3/config/spyder.ini
        section: ipython_console
        option: graphics_backend
        value: inline
        create: yes

    - name: Disable mute inline plotting
      ini_file:
        path: ~/.config/spyder-py3/config/spyder.ini
        section: ipython_console
        option: mute_inline_plotting
        value: 'False'
        create: yes

    - name: Set graphics format to SVG
      ini_file:
        path: ~/.config/spyder-py3/config/spyder.ini
        section: ipython_console
        option: graphics_format
        value: 'svg'
        create: yes